# Generated by Django 2.0.7 on 2018-07-17 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillingProfile',
        ),
    ]
