# Generated by Django 2.0.7 on 2018-08-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='billingAddressCountry',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
