# Generated by Django 2.0.7 on 2018-07-28 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0005_auto_20180728_1517'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='User',
        ),
    ]
