# Generated by Django 2.0.7 on 2018-07-17 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_charge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingprofile',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='billingprofile',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='billingprofile',
            name='stripe_id',
            field=models.CharField(max_length=255),
        ),
    ]
