# Generated by Django 2.0.7 on 2018-08-30 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_charge', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillingProfile',
        ),
    ]
