# Generated by Django 2.0.7 on 2018-07-27 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_charge', '0002_auto_20180717_2052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingprofile',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='billingprofile',
            old_name='last_name',
            new_name='stripeBillingAddressLine1',
        ),
    ]
