# Generated by Django 2.0.7 on 2018-07-27 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_charge', '0004_auto_20180727_0413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingprofile',
            old_name='stripe_id',
            new_name='chargeId',
        ),
    ]
