# Generated by Django 2.0.7 on 2018-07-28 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_charge', '0008_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
